---
- name: Install ipset and ferm
  apt:
    name:
      - ipset
      - ferm
    cache_valid_time: 600

- name: Remove ufw
  apt:
    name: ufw
    state: absent
    purge: yes
    force: yes

- name: Copy ipset_reload
  copy:
    src: ipset-reload.sh
    dest: /usr/local/bin/ipset-reload.sh
    mode: u=rxw,g=r,o=r
    owner: root
    group: root

- name: Create ipset tables
  template:
    src: ipset.tables.j2
    dest: /etc/ipset.tables
  notify:
    - Reload ipset tables
    - Reload ferm

- name: Copy /etc/default/ferm
  copy:
    src: default-ferm
    dest: /etc/default/ferm
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Reload ferm

- name: Generate /etc/ferm/ferm.conf
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
    mode: u=rw,g=r,o=r
    owner: root
    group: root
  notify: Reload ferm
